spring.application.name=projeto-mvc
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=N@th4_po

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true